server:
  port: 8080 # ??????????
spring:
  application:
    name: eureka-client-a
# ????????? ???????????????ip port ...? ???????????
eureka:
  client:
    service-url: # ???????
      defaultZone: http://localhost:8761/eureka