server:
  port: 8082
spring:
  application:
    name: teacher-service
  redis:
    password: javacppgorust
    host: 192.168.81.130
eureka:
  client:
    service-url:
      defaultZone: http://192.168.81.130:8761/eureka
    registry-fetch-interval-seconds: 3 # ?????????????
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

