server:
  port: 8081
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://192.168.81.130:8761/eureka
# feign??????????????? ????ribbon ?????????ribbon???
ribbon:
  ReadTimeout: 3000 # ?3s????
  ConnectTimeout: 3000 # ?????????
