server:
  port: 80
spring:
  application:
    name: nacos-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        namespace: e86f45ed-9601-4cde-ad77-5d84d5d58807
        group: A_GROUP
    gateway:
      discovery:
        locator:
          enabled: true # 开启动态路由
          lower-case-service-id: true
      enabled: true